---
version: '2'
services:
  db:
    image: mongo
    expose:
     - 27017
    ports:
     - 27017:27107
  web:
    image: craigbarrau/medrec-physicians
    ports:
      - 10010:10010
    depends_on:
      - db
